// bulk-upload.js
import { db } from "./firebase.js";

// 여기에 넣을 사이트 목록들
const sites = [
  // 🔹 self-caravan (자가 카라반존)
  {
    id: "CAR1",
    type: "self-caravan",
    name: "CAR1",
    zone: "자가 카라반존",
    isActive: true,
    carOption: "차박 전용",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 60000,
    priceOffWeekend: 65000,
    pricePeakWeekday: 70000,
    pricePeakWeekend: 75000,
  },
 {
    id: "CAR2",
    type: "self-caravan",
    name: "CAR2",
    zone: "자가 카라반존",
    isActive: true,
    carOption: "차박 전용",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 60000,
    priceOffWeekend: 65000,
    pricePeakWeekday: 70000,
    pricePeakWeekend: 75000,
  },
  {
    id: "CAR3",
    type: "self-caravan",
    name: "CAR3",
    zone: "자가 카라반존",
    isActive: true,
    carOption: "차박 전용",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 60000,
    priceOffWeekend: 65000,
    pricePeakWeekday: 70000,
    pricePeakWeekend: 75000,
  },
 {
    id: "CAR4",
    type: "self-caravan",
    name: "CAR4",
    zone: "자가 카라반존",
    isActive: true,
    carOption: "차박 전용",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 60000,
    priceOffWeekend: 65000,
    pricePeakWeekday: 70000,
    pricePeakWeekend: 75000,

  },
    {
    id: "CAR5",
    type: "self-caravan",
    name: "CAR5",
    zone: "자가 카라반존",
    isActive: true,
    carOption: "차박 전용",
    squareImg: "",
    images: [],

    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,

    priceOffWeekday: 60000,
    priceOffWeekend: 65000,
    pricePeakWeekday: 70000,
    pricePeakWeekend: 75000,
  },
 {
    id: "CAR6",
    type: "self-caravan",
    name: "CAR6",
    zone: "자가 카라반존",
    isActive: true,
    carOption: "차박 전용",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 60000,
    priceOffWeekend: 65000,
    pricePeakWeekday: 70000,
    pricePeakWeekend: 75000,
  },
   {
    id: "CAR7",
    type: "self-caravan",
    name: "CAR7",
    zone: "자가 카라반존",
    isActive: true,
    carOption: "차박 전용",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 60000,
    priceOffWeekend: 65000,
    pricePeakWeekday: 70000,
    pricePeakWeekend: 75000,
  },

  // 🔹 cabana-deck (카바나 데크존)
  {
    id: "CAB1",
    type: "cabana-deck",
    name: "CAB1",
    zone: "카바나 데크존",
    isActive: true,
    carOption: "차박 가능",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 50000,
    priceOffWeekend: 55000,
    pricePeakWeekday: 60000,
    pricePeakWeekend: 65000,
  },
    {
    id: "CAB2",
    type: "cabana-deck",
    name: "CAB2",
    zone: "카바나 데크존",
    isActive: true,
    carOption: "차박 가능",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 50000,
    priceOffWeekend: 55000,
    pricePeakWeekday: 60000,
    pricePeakWeekend: 65000,
  },
    {
    id: "CAB3",
    type: "cabana-deck",
    name: "CAB3",
    zone: "카바나 데크존",
    isActive: true,
    carOption: "차박 가능",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 50000,
    priceOffWeekend: 55000,
    pricePeakWeekday: 60000,
    pricePeakWeekend: 65000,
  },
      {
    id: "CAB4",
    type: "cabana-deck",
    name: "CAB4",
    zone: "카바나 데크존",

    isActive: true,
    carOption: "차박 가능",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 50000,
    priceOffWeekend: 55000,
    pricePeakWeekday: 60000,
    pricePeakWeekend: 65000,
  },
    {
    id: "CAB5",
    type: "cabana-deck",
    name: "CAB5",
    zone: "카바나 데크존",
    isActive: true,
    carOption: "차박 가능",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 50000,
    priceOffWeekend: 55000,
    pricePeakWeekday: 60000,
    pricePeakWeekend: 65000,
  },
      {
    id: "CAB6",
    type: "cabana-deck",
    name: "CAB6",
    zone: "카바나 데크존",
    isActive: true,
    carOption: "차박 가능",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 50000,
    priceOffWeekend: 55000,
    pricePeakWeekday: 60000,
    pricePeakWeekend: 65000,
  },
    {
    id: "CAB7",
    type: "cabana-deck",
    name: "CAB7",
    zone: "카바나 데크존",
    isActive: true,
    carOption: "차박 가능",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 50000,
    priceOffWeekend: 55000,
    pricePeakWeekday: 60000,
    pricePeakWeekend: 65000,
  },
    {
    id: "CAB8",
    type: "cabana-deck",
    name: "CAB8",
    zone: "카바나 데크존",
    isActive: true,
    carOption: "차박 가능",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 50000,
    priceOffWeekend: 55000,
    pricePeakWeekday: 60000,
    pricePeakWeekend: 65000,
  },

  // 🔹 캠핑 사이트 A
  {
    id: "A1",
    type: "tent",
    name: "A1",
    zone: "A존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "A2",
    type: "tent",
    name: "A2",
    zone: "A존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
  {
    id: "A3",
    type: "tent",
    name: "A3",
    zone: "A존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "A4",
    type: "tent",
    name: "A4",
    zone: "A존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
  {
    id: "A5",
    type: "tent",
    name: "A5",
    zone: "A존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "A6",
    type: "tent",
    name: "A6",
    zone: "A존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "A7",
    type: "tent",
    name: "A7",
    zone: "A존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "A8",
    type: "tent",
    name: "A8",
    zone: "A존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "A9",
    type: "tent",
    name: "A9",
    zone: "A존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "A10",
    type: "tent",
    name: "A10",
    zone: "A존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "A11",
    type: "tent",
    name: "A11",
    zone: "A존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "A12",
    type: "tent",
    name: "A12",
    zone: "A존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },


  // 🔹 캠핑 사이트 B
  {
    id: "B1",
    type: "tent",
    name: "B1",
    zone: "B존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "B2",
    type: "tent",
    name: "B2",
    zone: "B존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
  {
    id: "B3",
    type: "tent",
    name: "B3",
    zone: "B존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "B4",
    type: "tent",
    name: "B4",
    zone: "B존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
  {
    id: "B5",
    type: "tent",
    name: "B5",
    zone: "B존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "B6",
    type: "tent",
    name: "B6",
    zone: "B존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
  {
    id: "B7",
    type: "tent",
    name: "B7",
    zone: "B존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "B8",
    type: "tent",
    name: "B8",
    zone: "B존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
  {
    id: "B9",
    type: "tent",
    name: "B9",
    zone: "B존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "B10",
    type: "tent",
    name: "B10",
    zone: "B존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
  {
    id: "B11",
    type: "tent",
    name: "B11",
    zone: "B존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "B12",
    type: "tent",
    name: "B12",
    zone: "B존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "B13",
    type: "tent",
    name: "B13",
    zone: "B존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "B14",
    type: "tent",
    name: "B14",
    zone: "B존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
  {
    id: "B15",
    type: "tent",
    name: "B15",
    zone: "B존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "B16",
    type: "tent",
    name: "B16",
    zone: "B존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
  {
    id: "B17",
    type: "tent",
    name: "B17",
    zone: "B존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "B18",
    type: "tent",
    name: "B18",
    zone: "B존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
  {
    id: "B19",
    type: "tent",
    name: "B19",
    zone: "B존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },

  // 🔹 캠핑 사이트 E
  {
    id: "E1",
    type: "tent",
    name: "E1",
    zone: "E존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "E2",
    type: "tent",
    name: "E2",
    zone: "E존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "E3",
    type: "tent",
    name: "E3",
    zone: "E존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "E4",
    type: "tent",
    name: "E4",
    zone: "E존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "E5",
    type: "tent",
    name: "E5",
    zone: "E존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "E6",
    type: "tent",
    name: "E6",
    zone: "E존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "E7",
    type: "tent",
    name: "E7",
    zone: "E존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },

  

    // 🔹 캠핑 사이트 F
  {
    id: "F1",
    type: "tent",
    name: "F1",
    zone: "F존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "F2",
    type: "tent",
    name: "F2",
    zone: "F존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },
    {
    id: "F3",
    type: "tent",
    name: "F3",
    zone: "F존 캠핑 사이트",
    isActive: true,
    carOption: "차박 불가",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 35000,
    priceOffWeekend: 40000,
    pricePeakWeekday: 40000,
    pricePeakWeekend: 45000,
  },




  // 🔹 팬션
  {
    id: "D1",
    type: "pension",
    name: "D1",
    zone: "팬션",
    isActive: true,
    carOption: "",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 120000,
    priceOffWeekend: 130000,
    pricePeakWeekday: 130000,
    pricePeakWeekend: 140000,
  },
  {
    id: "D2",
    type: "pension",
    name: "D2",
    zone: "팬션",
    isActive: true,
    carOption: "",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 120000,
    priceOffWeekend: 130000,
    pricePeakWeekday: 130000,
    pricePeakWeekend: 140000,
  },
  {
    id: "D3",
    type: "pension",
    name: "D3",
    zone: "팬션",
    isActive: true,
    carOption: "",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 120000,
    priceOffWeekend: 130000,
    pricePeakWeekday: 130000,
    pricePeakWeekend: 140000,
  },
  {
    id: "D4",
    type: "pension",
    name: "D4",
    zone: "팬션",
    isActive: true,
    carOption: "",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 120000,
    priceOffWeekend: 130000,
    pricePeakWeekday: 130000,
    pricePeakWeekend: 140000,
  },
  {
    id: "D5",
    type: "pension",
    name: "D5",
    zone: "팬션",
    isActive: true,
    carOption: "",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 120000,
    priceOffWeekend: 130000,
    pricePeakWeekday: 130000,
    pricePeakWeekend: 140000,
  },
  {
    id: "D6",
    type: "pension",
    name: "D6",
    zone: "팬션",
    isActive: true,
    carOption: "",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 120000,
    priceOffWeekend: 130000,
    pricePeakWeekday: 130000,
    pricePeakWeekend: 140000,
  },
  {
    id: "D7",
    type: "pension",
    name: "D7",
    zone: "팬션",
    isActive: true,
    carOption: "",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 120000,
    priceOffWeekend: 130000,
    pricePeakWeekday: 130000,
    pricePeakWeekend: 140000,
  },
  {
    id: "D8",
    type: "pension",
    name: "D8",
    zone: "팬션",
    isActive: true,
    carOption: "",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 120000,
    priceOffWeekend: 130000,
    pricePeakWeekday: 130000,
    pricePeakWeekend: 140000,
  },
    {
    id: "D9",
    type: "pension",
    name: "D9",
    zone: "팬션",
    isActive: true,
    carOption: "",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 120000,
    priceOffWeekend: 130000,
    pricePeakWeekday: 130000,
    pricePeakWeekend: 140000,
  },
  {
    id: "D10",
    type: "pension",
    name: "D10",
    zone: "팬션",
    isActive: true,
    carOption: "",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 120000,
    priceOffWeekend: 130000,
    pricePeakWeekday: 130000,
    pricePeakWeekend: 140000,
  },
  {
    id: "D11",
    type: "pension",
    name: "D11",
    zone: "팬션",
    isActive: true,
    carOption: "",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 120000,
    priceOffWeekend: 130000,
    pricePeakWeekday: 130000,
    pricePeakWeekend: 140000,
  },
  {
    id: "D12",
    type: "pension",
    name: "D12",
    zone: "팬션",
    isActive: true,
    carOption: "",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 120000,
    priceOffWeekend: 130000,
    pricePeakWeekday: 130000,
    pricePeakWeekend: 140000,
  },
    {
    id: "D13",
    type: "pension",
    name: "D13",
    zone: "팬션",
    isActive: true,
    carOption: "",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 120000,
    priceOffWeekend: 130000,
    pricePeakWeekday: 130000,
    pricePeakWeekend: 140000,
  },
  {
    id: "D14",
    type: "pension",
    name: "D14",
    zone: "팬션",
    isActive: true,
    carOption: "",
    squareImg: "",
    images: [],
    basePeople: 4,
    maxPeople: 5,
    extraPerPerson: 10000,
    priceOffWeekday: 120000,
    priceOffWeekend: 130000,
    pricePeakWeekday: 130000,
    pricePeakWeekend: 140000,
  },

];

// 메인 업로드 함수
async function uploadSites() {
  try {
    const batch = db.batch();

    for (const site of sites) {
      const ref = db.collection("sites").doc(site.id); // 문서 ID를 id 필드와 맞춤
      batch.set(ref, site, { merge: true }); // 이미 있으면 덮어쓰고, 없으면 새로 생성
      console.log("큐에 추가:", site.id);
    }

    await batch.commit();
    console.log("✅ 모든 사이트 업로드 완료!");
  } catch (err) {
    console.error("🔥 업로드 중 오류:", err);
  } finally {
    process.exit(0);
  }
}

// 실행
uploadSites();
